### ISSUE TITLE
Live Reveal Slideshow feature is not working

### ISSUE THREAD

**Issue by tuvangezer** [Microsoft/AzureNotebooks#123]
### Description
I believe there is a problem with the preinstalled version of live reveal in the notebook servers, when I follow the steps from the github page of the live reveal extension in here https://github.com/damianavila/RISE I get a working slideshow for my local notebook, however when I press the "Enter exit live reveal slideshow" button on Azure it doesn't go to slide view and the buttons become unresponsive.

### Repro Steps
Just try to make a slideshow from notebook 
### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): Python 3
Web Browser: Chrome, Safari

**Comment by stebo85** [comment]
I have the same problem in Edge and Firefox and seems to be related to a mime mismatch? Any ideas for a workaround? 

Current window: notebooks.azure.com/n/g2IV3POfLP0/notebooks/Exercise_01.ipynb
No (or empty) RISE metadata. Using ONLY custom config (if exist) on top of the default config.
main.js (60,7)
SEC7113: CSS was ignored due to mime type mismatch
reveal.css
SEC7112: Script from https://notebooks.azure.com/n/g2IV3POfLP0/nbextensions/rise/static/reveal.js/lib/js/head.min.js?v=20170724040842&v=20170724040842 was blocked due to mime type mismatch
Exercise_01.ipynb
SCRIPT5022: Script error for "/n/g2IV3POfLP0/nbextensions/rise/static/reveal.js/lib/js/head.min.js?v=20170724040842"
http://requirejs.org/docs/errors.html#scripterror
require.js (140,9)
SCRIPT5022: Script error for "/n/g2IV3POfLP0/nbextensions/rise/static/reveal.js/js/reveal.js?v=20170724040842"
http://requirejs.org/docs/errors.html#scripterror
require.js (140,9)
SEC7112: Script from https://notebooks.azure.com/n/g2IV3POfLP0/nbextensions/rise/static/reveal.js/js/reveal.js?v=20170724040842&v=20170724040842 was blocked due to mime type mismatch
Exercise_01.ipynb
SEC7113: CSS was ignored due to mime type mismatch
simple.css

**Comment by denfromufa** [comment]
I have the same problem on Windows 10, Chrome:

![image](https://user-images.githubusercontent.com/7870949/28811570-c2e3822c-7655-11e7-9200-57bdd60943ce.png)

**Comment by crwilcox** [comment]
I believe this is fixed now. Can you verify? I don't have a link to your library that was causing the failure.

**Comment by stebo85** [comment]
Yes, it works perfectly now. Thank you for fixing this bug.

**Comment by crwilcox** [comment]
@stebo85 , thanks for getting back to me so quickly. I will close this issue. Thanks for helping us improve Azure Notebooks!
