### ISSUE TITLE
Guarantee execution time for instructor notebooks 

### ISSUE THREAD

**Issue by eclectir** [microsoft/AzureNotebooks#13]
For computationally heavy notebooks, instructor should be able to execute notebooks in a specific amount of time.

**Comment by crwilcox** [comment]
Do you have a suggestion for detecting instructors? What stops all users from saying they are instructors if we make this a sort of priority setting?

**Comment by crwilcox** [comment]
@smortaz, please attach this proposal you reference to this issue so it can be referenced and understood by all people viewing this issue. I was unable to discover what you are referring to.

**Comment by brettcannon** [comment]
I'm curious to see the design proposal as well since I'm not sure how you can guarantee execution time for arbitrary code in a notebook (e.g. how do you know a priori that a notebook would take 5 minutes or 5 hours to execute?). Now if the request is for priority execution so that a specific notebook is given priority on the machine (or scheduled on a machine with low load or even a dedicated machine), I view that as a different ask and a different problem to solve.

**Comment by smortaz** [comment]
i believe it was scheduling instructors or demoers on a low load machine,
not absolute guaranteed execution.

**Comment by crwilcox** [comment]
So, how do we determine instructors? What is the qualification for being an instructor? How do we fairly assign this to all instructors while not providing a checkbox to give anyone priority status on our system?

**Comment by smortaz** [comment]
the were was a thread on this if i recall.  my proposal was something along these lines:

- Instructor goes to aznb.com/instructor
- they fill out the form that basically asks for:
-- time, date, duration of talk (with reasonable limits)
-- link to announcement about the class/webinar/...
-- link to library

we get an email & check out the request & if approved, enable that login to have priority placement for the duration requested.

**Comment by smortaz** [comment]
Another approach is that we qualify a person to be an instructor (via the form above), then they get a check mark for priority placement.  this can last say, a quarter.  they can renew status periodically as needed.
