### ISSUE TITLE
Files on my notebook server are deleted every night.

### ISSUE THREAD

**Issue by tmthyjames** [Microsoft/AzureNotebooks#160]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com)

### Description
I was installing an extension I wrote last night on my Azure notebook server and this morning it was gone. The script I installed was in the `.ipython/profile_default/startup` directory. Is keep your dependencies a feature of the paid subscription? I'm on the free plan if that helps.

### Repro Steps
1) Run these commands (or just create a new file in this directory)
```
$ cd .ipython/profile_default/startup
$ git clone https://github.com/tmthyjames/SQLCell.git
$ cp SQLCell/sqlcell_app.py sqlcell_app.py
```
2) Wait 24 hours
3) Check to see if files are still there

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A): Python2
Occurrence Time: 
Web Browser: Chrome
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
@tmthyjames sorry I am just responding to this now. This is very much by design. As of today, we don't have free or paid plans. We only persist the content in ~/library though. If you want to install something on each run of a library you could use the environment setup steps feature under 'settings' of a library.

Thanks!
