### ISSUE TITLE
Link to files and directories from README.md

### ISSUE THREAD

**Issue by garth-wells** [microsoft/AzureNotebooks#193]
Markdown links in `README.md` are absolute rather than relative, e.g.

    [my directory](test_dir)

links to https://notebooks.azure.com/test_dir/. Relative links would be better.

**Comment by KieranBrantnerMagee** [comment]
Hey Garth,

Thanks for the ping!  Your ask seems quite reasonable, I've added it to our backlog, will follow up here as needed.

**Comment by tomkom** [comment]
What is currently the recommended way to link to nested folders in the library, from the root Readme? Relative paths do not work. [mynotebook](subfolder/mynotebook.ipynb) does fail. Seems something with different resolutions in the html and notebooks handling. Can you please clarify?

**Comment by KieranBrantnerMagee** [comment]
Hey TomKom,
Unfortunately we have not gotten to supporting relative paths yet for folders due to our web endpoints needing different prefixes for navigation vs. file view ("libraries/foo/**tree**" vs "libraries/foo/**html**")

The suggested workaround would likely be to use an absolute path.  See my sample library [Here](https://notebooks.azure.com/anon-jhu4eq/libraries/ReadmeLinkingTest) for examples of 3 methods one can currently use to link, and copied below for posterity in case that library gets deleted.

`[This is an absolute link to a nested folder](https://notebooks.azure.com/anon-jhu4eq/libraries/ReadmeLinkingTest/tree/testfolder)`
`[This is an absolute link to a nested file](https://notebooks.azure.com/anon-jhu4eq/libraries/ReadmeLinkingTest/html/testfolder/testfile.txt)`
`[This is an (kind-of) relative link to a nested file](testfolder/testfile.txt)`

Hope this helps, don't hesitate to follow up if any questions.

**Comment by rgovil17** [comment]
Is there any update in the case of relative links to folders?

**Comment by elly0t** [comment]
Is there any update?

**Comment by alaindet** [comment]
I'd love to have this feature

**Comment by omer-goder** [comment]
@KieranBrantnerMagee, thanks for the help.
is there a way that you know of to link a subfolder from a subfolder with a relative link?
(go back a subfolder, or several and then go into a different subfolder)

**Comment by Furqanmunir** [comment]
Please can you tell me how can we publish readme.md with oher folder files?

**Comment by Abezzam10** [comment]
I think Markup links in README.md are now relative and absolute. 
Check out this link for more: https://github.blog/2013-01-31-relative-links-in-markup-files/
