### ISSUE TITLE
Issue with js files used by Jupyter widgets

### ISSUE THREAD

**Issue by astrofrog** [Microsoft/AzureNotebooks#245]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I'm having issues getting some Jupyter widgets to work when used on notebooks.azure.com as opposed to e.g. mybinder.org. Specifically, the widgets I'm trying don't appear and I get the following errors in the JS console:

```
Did not load script at 'https://notebooks.azure.com/content/jupyter/5.0.0/ipyevents.js?v=20171128172333'
because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.
```

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Run the first two cells of the example.ipynb notebook here:

https://notebooks.azure.com/trobitaille/libraries/pywwt-web-example

and check the JS console.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

18:33 GMT on 28th November 2017

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify): Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue?

https://notebooks.azure.com/trobitaille/libraries/pywwt-web-example/html/example.ipynb

**Comment by astrofrog** [comment]
It looks like the served js files have an incorrect MIME type:

```
Content-Type: text/html; charset=utf-8
```

Can the server be configured to return a Content-type of text/javascript instead of text/html for js files?

**Comment by DinoV** [comment]
I think the real issue here is that we're actually missing this file...  Unfortunately it's not immediately clear to me where the file is coming from.  But we also should update ipywidgets as we're still on 7.0.0b7 and 7.0.5 is out now.

**Comment by DinoV** [comment]
And I'm guessing that file is coming from here: https://anaconda.org/astrofrog/ipyevents

It's odd that it ends up wanting to load the file from the root Jupyter install, I would expect it to want to load from somewhere else.  I think it should install it into the per-user notebook extension and then it should be served as static content from the notebook server instead of directly from the root of Jupyter.  Right now it's being installed into the conda env that's used for running the kernel, and that's a different Python install then what's actually running the notebook server.

I would expect a:

pip install --user ipyevents --upgrade-strategy only-if-needed

To get closer to getting this successfully installed, but I hit an issue with a broken symlink to nbextensions.  Even after that though it didn't load for me, so I think it's likely that it's trying to install this file and load it from the wrong spot.

**Comment by DinoV** [comment]
Okay, I managed to get it working, but it's kind of ugly:

# This is on pip, and properly installs the extension into the right Python environment
pip2 install ipyevents --upgrade-strategy only-if-needed --user
/usr/local/bin/jupyter nbextension enable --py --user ipyevents

# pywwt-web isn't published on pip, only conda, so we need to clone and
# install it from GitHub.

# pywwt-web uses npm, and expects 'node' not 'nodejs'
cp /usr/bin/nodejs ../.local/bin/node
PATH=$PATH:/home/nbuser/.local/bin
export PATH

git clone https://github.com/astrofrog/pywwt-web.git
cd pywwt-web
pip2 install --user -e .

/usr/local/bin/jupyter nbextension install --py --user pywwt_web                                            
/usr/local/bin/jupyter nbextension enable --py --user pywwt_web                                             

# Not sure if these are strictly needed, they're documented as being needed at
# https://github.com/astrofrog/pywwt-web but that may be a doc bug
pip2 install ipyvolume --upgrade-strategy only-if-needed --user
/usr/local/bin/jupyter nbextension install --py --user ipyvolume
/usr/local/bin/jupyter nbextension enable --py --user ipyvolume

After all of that the widget seemed to load and work for me!

**Comment by astrofrog** [comment]
@DinoV - thanks for the suggested workaround! I had not noticed that it was trying to load the js files from the root Jupyter install.

I have not yet made pywwt-web pip-installable, however I did prepare a conda package for it, so I'm surprised that isn't working correctly. I tried making it so the Azure environment is set up with a shell script - however the conda command is not found so I had to do:

```
/home/nbuser/anaconda3_420/bin/conda install -c astrofrog/label/dev pywwt-web -y
```

Could this explain the weird issues? Is there a better way to use conda from the shell script for things to work correctly? (I'd rather not use conda from the notebook)

**Comment by DinoV** [comment]
The reason why conda alone doesn't work is because it doesn't update the right Python.  For better or worse, there's a lot of Python's going on here, and only some of them are Conda environments.

- /home/nbcommon/anaconda2_501 Kernel for Python 2.7
- /home/nbcommon/anaconda3_420 Kernel for Python 3.5
- /home/nbcommon/anaconda3_501 Kernel for Python 3.6
- /usr/bin/python - System python, this is used to run the notebook server 
- /usr/bin/python3 - System python3, we use this for running other Python things (e.g. running the storage for the ~/library directory).

When you do a conda install you've updated the kernel to have things available, so at that point pywwt_web is available for input.  But you haven't updated the notebook server because that's running from a different Python, the system /usr/bin/python, and it's not a conda install.  So ultimately you need to install pywwt_web into the Python version you want to have that available and update the system Python to have the notebook extensions.  I realize that's confusing, but ultimately with so many Python's we need to pick one to run the notebook server, and picking the system Python means that it's not likely to get messed up by installing packages.

As far as the best way to install it you have it right now...  We're going to add some symlinks which will be something like ~/python27, ~/python35, and ~/python36 (and maybe a ~/python3) to allow some version resilience in the future.   

I think ultimately what we should do here though is support environment.yml as an optional setup step in the environment, and probably have a requirements.txt option for the notebook server, and then an option to select which notebook extensions to enable.  Let me know what you think.

**Comment by astrofrog** [comment]
@DinoV - thanks for the explanations! I agree that it would be nice to support environment.yml files to set up the conda environment.

In the mean time, I'm trying your instructions above and ran into an issue when trying to run ``pip2``:

```
nbuser@nbserver:~$ pip2 install ipyevents --upgrade-strategy only-if-needed --user
<snip>
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/home/nbuser/.local/share/jupyter/nbextensions/jupyter-js-wid
gets'
```

I got rid of the error by doing:

```
nbuser@nbserver:~$ rm /home/nbuser/.local/share/jupyter/nbextensions
nbuser@nbserver:~$ mkdir /home/nbuser/.local/share/jupyter/nbextensions
```

but just wanted to report that it didn't work out of the box.

**Comment by astrofrog** [comment]
Just FYI I also found that I had to use pip3 instead of pip2 to get things to work - but it all works fine now!

**Comment by astrofrog** [comment]
@DinoV - I have one remaining related question - I've put the commands needed to set up the environment in a shell script:

https://github.com/astrofrog/pywwt-web-example/blob/master/setup_azure

I tried setting it up so that the environment is set up by a shell script and I selected the above file, but it doesn't seem to work, and I end up having to run that script manually. Is there a way to access the log of the environment setup to see if anything went wrong? This is the library I'm using now:

https://notebooks.azure.com/trobitaille/libraries/pywwt-jupyter-example

**Comment by smortaz** [comment]
Thomas - a couple of things to look at:

https://notebooks.azure.com/help/libraries/library-settings/environment

https://notebooks.azure.com/help/jupyter-notebooks/server-initialization



On Thu, Nov 30, 2017 at 4:26 AM, Thomas Robitaille <notifications@github.com

**Comment by astrofrog** [comment]
@smortaz - thanks! I have some residual issues related to that but my original issue here has been resolved, so I'll close this.
