### ISSUE TITLE
internal error while creating notebook server (f38e4c34-bbc9-4db5-928b-5db93b4f8b86) at 12/18/2017 7:33:44 AM

### ISSUE THREAD

**Issue by avinashsai** [microsoft/AzureNotebooks#262]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by avinashsai** [comment]
I used  https://notebooks.azure.com
Kernel used is Python 3.5 , the browser is Google Chrome , OS is windows 8.1
Path to the file : https://notebooks.azure.com/run/avinashmadasu/Ensemble?dest=%2Fnotebooks%2FFifth%20Dataset%2FDoc2Vec%20and%20ensemble%20on%20large%20movie.ipynb

I have been trying to use the notebook since early morning but an internal error message is popping out  every time I tried to do so. Please look into this issue as soon as possible.

**Comment by ozbonus** [comment]
I am also having this error at the moment with all kernels, old notebooks and new, even the sample ones provided by Microsoft. This is on the Android Nougat version of Chrome. This has been going on for at least the last 30 minutes.

**Comment by TIXFeniks** [comment]
We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: Internal error while creating notebook server (8115e408-bda0-4dfe-9c29-245150558ee7) at 12/18/2017 8:17:33 AM - same here

**Comment by smortaz** [comment]
Hi everyone - there is an issue that we shouldn't show that error and instead reject the URL format.  But the core of the problem is that whoever shared that URL with you needs to use the proper format.  

Specifically, this is wrong:

https://notebooks.azure.com/RUN/avinashmadasu/... 

Note the **RUN** node in the path.  The proper format is:

https://notebooks.azure.com/SomeUsername/SomeLibraryName/...

(note the absence of the word **RUN** in the path)

Please contact the person that provided you the URL and ask them to avoid the URL format with **RUN** in the URL by reading this thread.

Specifically for this **improperly** formed path in the 1st bug report:

https://notebooks.azure.com/run/avinashmadasu/Ensemble?dest=%2Fnotebooks%2FFifth%20Dataset%2FDoc2Vec%20and%20ensemble%20on%20large%20movie.ipynb

The proper format is:

https://notebooks.azure.com/avinashmadasu/libraries/Ensemble/html/First%20dataset/doc2vec%20and%20ensemble%20on%20cornell%20part%20dataset.ipynb

Thanks.
