### ISSUE TITLE
Download CSV file to assign folder

### ISSUE THREAD

**Issue by yianchen** [Microsoft/AzureNotebooks#274]
Hi there,

I want to extract some data from web and save it to specific folder in CSV format.
When I ran the scripts from Jupyter Notebook and saved the file to a local folder on Mac, it worked well. However, when I ran the scripts from Azure Notebook and wanted to save the file to an assigned folder (C:\Users\XYZazure\Desktop\Model_Info) on a VM, I kept getting FileNotFoundError even though I have already created a folder and used absolute path in the scripts. I have tried to replace \ with \\ and / , both didn't work. 

Error message I got: 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XYZazure\\Desktop\\Model_Info\\_FileName_Date.csv'

#### Which site did you access us from?
    [v] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [v] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Taipei time 2018/1/1 18:30~ 21:30  (tested on MacOS 10.12.6 & Windows Server 2016 Datacenter (VM))
Taipei time 2018/1/2 19:30 (tested on Windows 10 Enterprise)

#### Which Web Browser(s) did you see the error in?
    [v] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [v] Windows Server 2016 Datacenter (VM) and Windows 10 Enterprise
    [v] MacOS 10.12.6 
    [] Ubuntu
    [] Other (Please Specify)

**Comment by crwilcox** [comment]
Azure Notebooks is on linux and a windows style path won't work. You are using C: which is a denotation for a drive called C on windows. if you change that path to look like `/home/nbuser/Model_Info` it should work

**Comment by yianchen** [comment]
Hi Christopher,

Thank you for your reply.
I changed the path as suggested, but still got the same error message,
FileNotFoundError.

My NB runs on windows 10 enterprise, not on Linux.
I run scripts on Azure Notebook and want to save CSV file to a local
folder. How to I revise my directory? Thank you for your help in advance.

I tried:
"Home\\Users\\ann.ya_chen\\Desktop\\Model_Info"
"Home/Users/ann.ya_chen/Desktop/Model_Info"


BR,

Ann

On Thu, Jan 4, 2018 at 8:09 AM, Christopher Wilcox <notifications@github.com

**Comment by smortaz** [comment]
The separator in windows is \
The separator in Linux is /

Change \\ to /

**Comment by crwilcox** [comment]
@yianchen, 

Neither of those are paths that make sense on our Linux system. Assuming you want your model to persist, alongside your notebook files, you likely want to save it to `/home/nbuser/library/Model_Info`. The `/home/nbuser/library' directory is where all of your library content is stored.

NOTE: keep in mind that this directory, `/home/nbuser/library` is persisted. Because of this requirement, writes here are slower than to a local disk. If you are less concerned about storing what is in the 'model_info' folder, you can instead use a temporary directory. Python docs for interacting with temp files/directories: https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp
