### ISSUE TITLE
Feature request - Import from Visual Studio Team Services

### ISSUE THREAD

**Issue by propriocept** [microsoft/AzureNotebooks#278]
We are storing our internal Jupyter Notebooks in VSTS, but that doesn't support displaying/running them yet. It would be nice if we could import/clone our notebooks directly from VSTS, just like one can do now from GitHub.

**Comment by crwilcox** [comment]
@propriocept, thanks for the feature request.

In the meanwhile, you can get your VSTS content into your notebook. If you go to the terminal (there is a terminal button on your library page), you can git clone into your /home/nbuser/library folder and it will be persisted.

Thanks!
Chris

**Comment by crwilcox** [comment]
@binnisb , It is a public service and, while I wouldn't encourage you to put highly sensitive content on it, I believe our system to be secure. You are isolated from other users via a hypervisor. While this is not impenetrable, it is considered a sound isolation practice.

Thanks!

**Comment by JontySinai** [comment]
Any update on this? Would also like to see proper integration with Azure DevOps (formerly VSTS). Would also like to see proper integration with an Azure account, so that:

- I can fetch data from an Azure Storage account without compromising keys
- I can access the latest builds from my an Azure Devops repos directly
- I can work seamlessly with other users in my team
- My Azure Notebooks account is the same as my Azure account
- I can host my Azure Notebooks on my Azure subscription
- I can use compute from my Azure subscription automatically

**Comment by kiranpvuthaman** [comment]
Any update on Integration with VSTS Git Repository? Iam also behind the same functionalities JontySinai is having above.

**Comment by orion1900** [comment]
Is this feature request even on the radar? I would think integration with Azure DevOps would tickle some Microsoft Marketing manager enough, for them to start pushing this.
