### ISSUE TITLE
'IOPub data rate exceeded' error

### ISSUE THREAD

**Issue by garth-wells** [Microsoft/AzureNotebooks#286]
I've started seeing the below error for the notebook at https://notebooks.azure.com/garth-wells/libraries/cued-ia-ex-paper-guidance. It worked fine until recently, and works fine when running Jupyter locally.

```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
```

**Comment by garth-wells** [comment]
https://github.com/jupyter/notebook/issues/2287

**Comment by smortaz** [comment]
Thx for the report. Could be due to removing the white list but limiting
network traffic rate feature.

@chris?

**Comment by minrk** [comment]
This is fixed in notebook 5.1 (current is 5.3.0), but the notebook server run on azure (in /usr/local) is 5.0.0. Upgrading the notebook server ought to be the fix. If that's undesirable or unavailable, setting `c.NotebookApp.iopub_data_rate_limit = 0` will disable the rate limit altogether, which can be done in `/etc/jupyter/jupyter_notebook_config.py` or `~/.jupyter/jupyter_notebook_config.py`.

**Comment by smortaz** [comment]
Thanks @minrk !

**Comment by smortaz** [comment]
Ok thanks @minrk  - happy that this isnt related to the network rate limit we've added.  I think dino is upgrading jupyter this week to the near latest version. Saw a PR go by.

PS I'm hoping to setup a mtg in early march at UCB to discuss adding the debugger and other topics - hopefully we'll see you.

**Comment by minrk** [comment]
Awesome! I'm not at Berkeley anymore, but there's loads of great JupyterHub folks there.

**Comment by garth-wells** [comment]
Update to Jupyter 5.3. has resolved the issue. Thanks!
