### ISSUE TITLE
Workaround to handle bigger git repositories

### ISSUE THREAD

**Issue by whatevergeek** [Microsoft/AzureNotebooks#298]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    https://notebooks.azure.com

#### Describe the issue you are encountering
This Git repository exceeds the size allowed in a library (1GB).
![image](https://user-images.githubusercontent.com/7351683/35679601-9cbf8eb4-0792-11e8-8194-eff49fca3ae1.png)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
You can clone this repository in an azure notebooks library:
https://github.com/Horea94/Fruit-Images-Dataset

#### Which language/kernel were you using when you experienced this issue?
N/A

#### What time (please include time zone) did this occur?
9pm SGT

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, N/A
N/A
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them N/A

Please provide a workaround for working with bigger respository inside Azure Notebooks.
Perhaps,  ability to refer to an Azure storage, etc. that we can still access from Azure Notebooks.

**Comment by crwilcox** [comment]
Presently, Azure Notebooks limits each library to 1GB. So there isn't really a way to get around what you are seeing. You could pare down the repository to the content you need if that was able to get it below 1GB Or separate the repository into a few different libraries.

Thanks!
Chris

**Comment by whatevergeek** [comment]
hmm... does that mean we couldn't use azure notebooks to train huge set of pictures for deep learning? :-(

**Comment by crwilcox** [comment]
As of now there are no concrete plans to increase the size of a library beyond 1GB. I can't speak for the future. If you wish to train using deep learning and have a large dataset (> 1GB), you could also look into using Azure's Data Science VM offering. You can leverage more CPU/Memory or GPU.
https://azure.microsoft.com/en-us/services/virtual-machines/data-science-virtual-machines/

**Comment by crwilcox** [comment]
This issue is resolved. The request was for a workaround to the storage size. I explained our support, limitations, and possible mitigations. I have been making an active effort to not leave questions open and collecting dust. If you believe your original question wasn't addressed we can reopen this. If you now have additional feature requests, such as 'increase library size restriction to xGB', you could file an issue for that.

In #31 you reference the idea of Azure Blob Storage. You could today use that. The only part of Azure Notebooks limited to 1GB is your library folder (`~/library`). You can write to temp in excess of that if necessary, and python has terrific Azure SDK support that can be used today. https://docs.microsoft.com/en-us/azure/storage/blobs/storage-python-how-to-use-blob-storage

Please note that the only data persisted is what is in the ~/library folder. So if you do leverage the temp directory, you will need to move changes to ~/library if you wish them to be persisted across runs.

-Chris

**Comment by whatevergeek** [comment]
thanks for the responses @crwilcox 
is there a limit to the temp folder (/tmp)?
what i'm thinking is... one can download the images for training (can be more than 1gb)
to the temp folder... 
then run python via jupyter for training referencing the images... 
would this work?

**Comment by crwilcox** [comment]
Yep. that should work. As far as the size of tmp, the limit is on the disk of the machine. We have changed these over time. If you stay under 10GB I would imagine you would be alright.
I haven't really tested using with large amounts of data, but it is a useful strategy for large files as well as noisy write operations. Because we don't persist tmp reads/writes are faster than those to/from ~/library. So using tmp is both allowed to be bigger than 1GB and likely a bit snappier.
