### ISSUE TITLE
Add GPU support for Deep Learning

### ISSUE THREAD

**Issue by wihl** [microsoft/AzureNotebooks#31]
Please consider the template below to file your issue. 

### Description

For any practical Deep Learning application, GPU support is required. It should be possible to execute the notebook on a GPU supported machine. 

### Repro Steps

Install Tensorflow

Execute the basic testing script `tensorflow.models.image.mnist.convolutional`

On a GPU enabled machine, this takes less than two minutes. On a non GPU machine, it could take hours.

### Usage Scenario (e.g. teaching a computing course at university foo)

This is intended to be used at Harvard's CS109b Advanced Data Science course.

Note that other Deep Learning courses use GPU instances:

 http://cs224d.stanford.edu/supplementary/aws-tutorial-2.pdf

http://cs231n.github.io/aws-tutorial/

http://rll.berkeley.edu/deeprlcourse/

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): Python2, CUDA, cudnn, Tensorflow

**Comment by versae** [comment]
Any update on this? Just discovered that Google CoLab now has free GPUs for up to 12hours.

**Comment by smortaz** [comment]
Hi Javier - we're looking at how we can provide GPU support, but nothing in
the very immediate future.

**Comment by michhar** [comment]
@smortaz and @whatevergeek - We've also had customers ask for this.  I generally point people to the Deep Learning Virtual Machine on Azure, as it can be set up for multi-tenant Jupyter and has GPU backend with all the data science ecosystem of tools (like Azure Notebooks, but GPU too), but it doesn't have a free tier - a few hours with a GPU-accelerated notebook system might be nice.  I know it's not really in scope likely, but just letting you know it's a popular ask.

**Comment by whatevergeek** [comment]
@michhar yup, i'm using DLVM... i shared it in the community in our area last week... not free and we need to be vigilant on pricing  and turning it off after use (otherwise, it'll drain your credit in just a day or two :-P )

anyway, user experience and feature set wise, i still prefer Azure Notebooks over Google Colab... especially the support of Juypter Lab! kudos to the team on this... 

on the otherhand, deep learning courses (such as http://www.fast.ai/ ) require their notebooks to be on GPU... there are a few ways of doing this... one of which is to setup on DLVM... other ones on other clouds...

however, currently for this use case, Google Colab provides such GPU platform for free...
i'm guessing it will attract and move such people  towards Google Colab...
https://towardsdatascience.com/fast-ai-lesson-1-on-google-colab-free-gpu-d2af89f53604

I understand that there might be a challenge on Microsoft side... as such resource has associated costs also... I had a discussion with Shahrokh on this... so I kinda understand... and I'm glad your team is looking into this...

I don't know also how long will Google have it for free.
Just a thought, would Azure Notebooks be able to match at least for the moment?
i.e. while Google is providing it for free?

Azure Notebooks is really a great platform... we don't wanna see people churn just for the sake of GPU... hehehe :-)

**Comment by whatevergeek** [comment]
btw, regarding deep learning... apart from GPU, we might need to consider the library size also...
as deep learning would need huge data...
currently, there's a limit of 1gb... 
perhaps, there's a limit on the platform... anyway, can the team explore if we can make other storage options? e.g. azure blog storage, etc for such purpose?
maybe an ability to easily mount them as a drive accessible to Azure Notebooks?

i raised a separate ticket but it was closed fast :-( 
https://github.com/Microsoft/AzureNotebooks/issues/298#event-1453342647

**Comment by whatevergeek** [comment]
dear friends,

just an update.
apart for google colaboratory...
i just learned that ibm cloud is also offering some free GPU for their jupyter platform via PowerAI:
https://developer.ibm.com/linuxonpower/deep-learning-powerai/

i've just confirmed by trying it... see below screenshot:
![image](https://user-images.githubusercontent.com/7351683/36064382-3f6a7c30-0ec5-11e8-8f63-f94c023b7e38.png)

really looking forward to azure notebook implementation...

**Comment by smortaz** [comment]
Thanks Paul!

Really happy to see IBM provide GPU as well.  Hopefully we can do some sort
of free GPU scenario as well.  As mentioned in a previous thread, it won't
in the very near future, but we're definitely looking at options!

Cheers,

s

**Comment by luisgizirian** [comment]
GPU (NVIDIA) support in some way (free-freemium-paid only) is a must to avoid loosing data-scientists to other providers when going thru deep learning courses (i.e. Fast.ai). @smortaz, I read you'll be looking into options. Please get "the board" to consider winning a bunch of potential "loyalists" to speed up offering such option. Thanks!

**Comment by somnathrakshit** [comment]
Hi, any news on free GPU for Azure notebooks?

**Comment by douglas125** [comment]
Another interesting option would be to allow users to choose Azure VM instances that would run the notebooks (even if it is not free), somewhat like Amazon deep learning AMI without the hassle. Of course we would need to be able to install all packages and do some custom configurations if needed...

**Comment by whatevergeek** [comment]
@douglas125 that option is always there... we use DLVM for such usually...
just that Google colab is offering GPU for free... so was hoping azure notebooks would have something also... so currently if people want free GPU, they go to colab

**Comment by denfromufa** [comment]
GPU and DSVM announcement today - sign me up!

https://github.com/Microsoft/AzureNotebooks/wiki/Azure-Notebooks-at-Microsoft-Connect()-2018#gpu

**Comment by tomkom** [comment]
I would like to enquire about the support for this feature. I am working at a University with an institutional subscription to Azure, and we are using notebooks in teaching. WOuld be great to be able to demonstrate this feature and not exit to Collab. Can you sign me in for the pilot please?

**Comment by yoavram** [comment]
Me too.

**Comment by KentoNishi** [comment]
Is there any update to this? I've been looking to use AzureNB, but Colab may be better for training,

**Comment by neaorin** [comment]
Another vote for this feature. It's incredibly frustrating not being able to get students to try out deep learning in Azure because of this limitation.

**Comment by Javortper** [comment]
We need this!

**Comment by etatbak** [comment]
Hi, is there any update for gpu (tensorflow) support by Azure?

**Comment by zafercavdar** [comment]
> Hi, is there any update for gpu (tensorflow) support by Azure?

Not yet.

**Comment by KentoNishi** [comment]
@zafercavdar what's preventing Azure from enabling this feature? Choosing a more powerful VM for the notebook environment sounds fairly straightforward to implement.

**Comment by akaszynski** [comment]
I've been running into issues a GPU enabled jupyterhub tensorflow environment enabled on Azure on my own (and outside of azure-notebooks).  I think that part of the issue might be due to the version of the nvidia enabled kernel and the nvidia-drivers.  This mismatch is making it quite challenging to install the correct version of the drivers on single user jupyterhub image.

It would be great if Azure could provide a walkthrough and image based off of jupyterhub/singleuser with the correct cuda libraries and nvidia drivers based on their azure kernel.
