### ISSUE TITLE
Cannot connect to sheetsu.com via requests.get()

### ISSUE THREAD

**Issue by adamharder** [Microsoft/AzureNotebooks#32]
Please consider the template below to file your issue. 

### Description
cannot connect to sheetsu.com via requests.get(). I get a 'Cannot connect to proxy' error

### Repro Steps
```

import requests
all_records_j=requests.get("https://www.sheetsu.com")

```
returns
```
ProxyErrorTraceback (most recent call last)
<ipython-input-7-a15240f1b9c7> in <module>()
      1 import requests
----> 2 all_records_j=requests.get("https://www.sheetsu.com")

/home/nbuser/anaconda2_410/lib/python2.7/site-packages/requests/api.pyc in get(url, params, **kwargs)
     69 
     70     kwargs.setdefault('allow_redirects', True)
---> 71     return request('get', url, params=params, **kwargs)
     72 
     73 

/home/nbuser/anaconda2_410/lib/python2.7/site-packages/requests/api.pyc in request(method, url, **kwargs)
     55     # cases, and look like a memory leak in others.
     56     with sessions.Session() as session:
---> 57         return session.request(method=method, url=url, **kwargs)
     58 
     59 

/home/nbuser/anaconda2_410/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    473         }
    474         send_kwargs.update(settings)
--> 475         resp = self.send(prep, **send_kwargs)
    476 
    477         return resp

/home/nbuser/anaconda2_410/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    583 
    584         # Send the request
--> 585         r = adapter.send(request, **kwargs)
    586 
    587         # Total elapsed time of the request (approximately)

/home/nbuser/anaconda2_410/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    463 
    464             if isinstance(e.reason, _ProxyError):
--> 465                 raise ProxyError(e, request=request)
    466 
    467             raise ConnectionError(e, request=request)

ProxyError: HTTPSConnectionPool(host='www.sheetsu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))

```

### Usage Scenario:

trying to access data from a google spreadsheet 

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time: 1/3/16 
Web Browser: chrome
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
Hi @adamharder.

Sorry you experienced difficulty. I have whitelisted that domain. You should be able to access it now.

Thanks!
Chris

**Comment by curtlyn** [comment]
I believe I am running into the exact same problem with congress.gov. Is it possible to whitelist that too?

ProxyError                                Traceback (most recent call last)
<ipython-input-16-d0dcd323c187> in <module>()
      2 
      3 for bill in urlList:
----> 4     base = fetch_base(bill[0])
      5     if noAmdtCheck(base) == "FALSE":
      6         soup = fetch_soup(base,bill[0])

<ipython-input-8-34b4f0fafbea> in fetch_base(url)
      1 def fetch_base(url):
----> 2     req = requests.get(url)
      3     base = BeautifulSoup(req.text,'lxml')
      4 
      5     return base

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/requests/api.py in get(url, params, **kwargs)
     68 
     69     kwargs.setdefault('allow_redirects', True)
---> 70     return request('get', url, params=params, **kwargs)
     71 
     72 

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/requests/api.py in request(method, url, **kwargs)
     54     # cases, and look like a memory leak in others.
     55     with sessions.Session() as session:
---> 56         return session.request(method=method, url=url, **kwargs)
     57 
     58 

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    486         }
    487         send_kwargs.update(settings)
--> 488         resp = self.send(prep, **send_kwargs)
    489 
    490         return resp

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/requests/sessions.py in send(self, request, **kwargs)
    607 
    608         # Send the request
--> 609         r = adapter.send(request, **kwargs)
    610 
    611         # Total elapsed time of the request (approximately)

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    483 
    484             if isinstance(e.reason, _ProxyError):
--> 485                 raise ProxyError(e, request=request)
    486 
    487             raise ConnectionError(e, request=request)

ProxyError: HTTPSConnectionPool(host='www.congress.gov', port=443): Max retries exceeded with url: /bill/108th-congress/house-bill/2673/amendments (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

**Comment by crwilcox** [comment]
@curtlyn , I just added congress.gov.

**Comment by rhennig** [comment]
I am trying to connect to the materialsproject.org using the Azure notebook and have the same issue. Could this be added to the whitelist? Thanks for your help.

ProxyError: HTTPSConnectionPool(host='www.materialsproject.org', port=443): Max retries exceeded with url: /rest/v2/materials/LiBeH3/vasp/final_structure (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

**Comment by crwilcox** [comment]
@rhennig , sorry this got lost. In the future, for the best response, I suggest opening a new issue. I have added materialsproject to our whitelist.
