### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by SebastianLindner** [Microsoft/AzureNotebooks#324]
Hi... first of all many thanks for this great service.

Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Transport endpoint is not connected

#### What steps can we take to reproduce this issue?

When I try to download a bigger dataset as a zip file, the download always aborts. I tried downloading files with a couple of methods (wget, curl, short python snippet) e.g. 

!wget http://images.cocodataset.org/zips/val2014.zip

Error:
Cannot write to 'val2014.zip' (Transport endpoint is not connected).

Weirdly enough, this problem only occurs if I use Azure Notebook via https://notebooks.azure.com.
On https://studio.azureml.net downloading went perfectly fine.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Germany UTC+2

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by crwilcox** [comment]
It would appear this zip is larger than 1GB. A library on Azure Notebooks is only allowed to be 1GB in size. The area that is limited to this 1GB restriction is ~/library. That is the running directory of a notebook. You can write larger files to areas outside of ~/library. For instance, if you instead run `!curl http://images.cocodataset.org/zips/val2014.zip -o ~/val2014.zip` the large file will be written outside of the persisted area of the library.

Please note, because that area isn't persisted, each time you come back to Azure Notebooks, you will need to re-download that zip as it isn't persisted like the rest of your files.

Thanks!

**Comment by SebastianLindner** [comment]
Thanks for the quick response! Did read anywhere that there is a file size limit....

**Comment by crwilcox** [comment]
@SebastianLindner , you are very welcome. We mention the limit in our help documentation's introduction page

> Current Service limitations 
> The service is free but there are network limitations to prevent abuse.  We have white-listed lots of
> data sources and services and regularly add more per user requests. 
> There is a 4G memory limit per user and a 1G data limit. 
https://notebooks.azure.com/help/introduction
