### ISSUE TITLE
Allow custom VM size

### ISSUE THREAD

**Issue by nhirschey** [Microsoft/AzureNotebooks#337]
Notebooks are currently limited to 4gb of RAM and a few logical processors. It would be nice to be able to use a notebook backed by a large VM with lots of RAM and many CPU cores. I cannot use the azure implementation of notebooks because of these limitations.

I am aware of the Data Science VM. Notebooks are a simpler and superior front-end.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Which language/kernel were you using when you experienced this issue?

    [*] R 
    [*] F#

**Comment by smortaz** [comment]
Hi @nhirschey  - this feature is high on our todo list.  Stay tuned!

**Comment by edervishaj** [comment]
Any update on whether the Azure Notebooks will feature higher RAM/CPU cores limitations?

**Comment by andneilmsft** [comment]
Thanks for getting in touch. What compute options would you like to see?

**Comment by edervishaj** [comment]
> Thanks for getting in touch. What compute options would you like to see?

Thanks for replying back!
In my honest opinion a VM with 4 cores and 16GB memory should satisfy most users for beginner to lower intermediate problems. I used Azure Notebooks for my recommender systems course (very sparse and big matrix-matrix multiplications) along side my local machine and I used the Python multithreading module thinking that all 8 cores were available. Later I double checked because my local machine (dual core) was running more or less in the same time. Also 4GB is very restrictive even for small datasets today because you have to keep track and free memory by deleting dataframes and/or big numpy arrays.
Thanks for this project! Really helpful!

**Comment by jflam** [comment]
That amount of compute will definitely fall into our paid compute options. However the cost is reasonable - if you want 4 dedicated cores, 14GB RAM, that's $0.52/hour. A 6 core, 56GB RAM with a K80 GPU is $1.30/hour.

Does that sound reasonable?

**Comment by nhirschey** [comment]
@jflam, paid compute with arbitrarily sized backing VMs would be great. I know I can set up a VM myself if I really have to, but a notebook with an “auto scaling” slider similar to what was or used to be available with Azure websites would be great. 

The killer feature would be a simple notebook front end that you could scale to the largest azure VM when needed using a simple slider. Paying for the VM cost is expected and completely reasonable.

**Comment by edervishaj** [comment]
@jflam are these prices from Azure Machine Learning Service? They surely sounds reasonable. Being a student I think I can make use of those specs with the free trial.
Thanks!
