### ISSUE TITLE
convert existing notebook to have github integration

### ISSUE THREAD

**Issue by ahnitz** [microsoft/AzureNotebooks#340]
#### Which site did you access us from?
    [*] https://notebooks.azure.com

#### Describe the issue you are encountering

I have an existing notebook that was created before github integration was added. Is there a way to convert the existing library to be linked to a github repo? I'd prefer not to have to start a new library, since it has been cloned many times and we have existing documentation, etc that links to this.

(https://notebooks.azure.com/nitz/libraries/pycbc)

**Comment by smortaz** [comment]
Hi. There is no direct support for git yet other than dropping into the
terminal and use git commands directly.   The load from GitHub basically
just copies it over. It doesn’t create a fancy git connection that you can
push/pull from.

 See here for the general steps:

https://medium.com/@mikeclymer/integrating-azure-notebooks-jupyter-notebooks-with-github-fd847e941e4

**Comment by smortaz** [comment]
It should.  However,  if you already have your stuff up to date on github, i'd pull that and follow the steps in the Medium article for pushing/pulling to/from github.    PS better git integration is coming in the JupyterLab environment, that's why we havent put a ton of calories into git integration for bare notebooks...
