### ISSUE TITLE
F# Notebooks: XPlot.Plotly charts fail 

### ISSUE THREAD

**Issue by mathias-brandewinder** [Microsoft/AzureNotebooks#36]
### Description

Using XPlot.Plotly to generate charts in F# Notebooks appears to be broken; I believe it worked a couple of days ago.

### Repro Steps

- Go to https://notebooks.azure.com/#sample-redirect 
- Open the "Introduction to F#" notebook.
- Select "Cells / Run All"
- The cell "Charts", containing

```
#load "XPlot.Plotly.Paket.fsx"
#load "XPlot.Plotly.fsx"
open XPlot.Plotly
```
... produces an error:  

```
System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/nbcommon/ifsharp/bin/paket-files/include-scripts/net451/include.main.group.fsx".
// more stuff
```

Note that the path in question, `include-scripts/net451/include.main.group.fsx`, doesn't match the path specified earlier in the notebook, `#load "paket-files/include-scripts/net45/include.main.group.fsx"`

### Usage Scenario

Simply trying to run samples and create my own workbooks.

### Recommended Metadata

The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time: 2/2/2017, around 20:00
Web Browser: Chrome
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
Thanks for reporting this. We are investigating this now and can hopefully get back to you shortly.

**Comment by crwilcox** [comment]
It seems the version of IFSharp we use isn't quite right. I will be upgrading that to be the bits at 43a0dc2e434568a0d491896461c4af682fa9b793 of IFSharp.

**Comment by crwilcox** [comment]
Fix deployed.

**Comment by mathias-brandewinder** [comment]
Yes! I can confirm it works, thanks a ton :)

**Comment by roguetrainer** [comment]
As a postscript, can we expect XPlot.GoogleCharts to render in Azure notebooks? I can get the sample code from the XPlot docs for GoogleCharts to run in Azure (https://github.com/TahaHachana/XPlot/tree/master/docs/content/chart), but the result does not render. We see instead an expression: 

XPlot.GoogleCharts.GoogleChart {Height = 250;
                                Id = "93453ca2-3432-4b46-b773-c2856040e6e2";
                                Width = 600;}

Is that the expected behaviour? Is there an extra command to get GoogleCharts to render or are they unsupported? Thanks for any advice.

**Comment by roguetrainer** [comment]
By complete coincidence it looks like this is work in progress as I type!
https://github.com/fsprojects/IfSharp/issues/118 
Nice work IfSharp team. Amazing.

**Comment by xperiandri** [comment]
@crwilcox, charts in Azure Notebooks F# tutorial do not work

Instead of charts I see
![image](https://user-images.githubusercontent.com/2365592/30338791-79496282-97f5-11e7-955b-44f2ee7244ce.png)

**Comment by crwilcox** [comment]
@xperiandri , is that on a preview?

**Comment by xperiandri** [comment]
What do you mean on Preview? On Azure Notebooks web site label says "Preview"

**Comment by crwilcox** [comment]
@xperiandri I was asking about the url of the site you provided the screenshot of. My guess was that it was the HTML preview, now a running notebook.

**Comment by xperiandri** [comment]
It was just an F# tutorial on Azure Notebook.
https://notebooks.azure.com/Microsoft/libraries/fsharp/html/FSharp%20for%20Azure%20Notebooks.ipynb

**Comment by crwilcox** [comment]
@xperiandri , if you see in the link, there is an /html/ portion. The page you are looking at is a rendering of what is in the executable notebook. Due to security concerns, we do not render javascript on these previews. If you clone and run this library, you should be able to see the graphic that isn't rendering.

**Comment by xperiandri** [comment]
Then you must at least display warning in place with explanation.
Unless that it looks like a not working product.
