### ISSUE TITLE
Notebook instance wont shutdown

### ISSUE THREAD

**Issue by anarchy89** [Microsoft/AzureNotebooks#365]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I am trying to shutdown a notebook by pressing the shutdown button but i get the following error, then i get the following prompt, 

"Your notebook server will be shutdown. Any unsaved state will be lost.

Do you want to continue?"

 When i click OK, it says "Internal Server Error" in red
#### Which language/kernel were you using when you experienced this issue?
    [x] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
GMT 8+
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by rcanand** [comment]
I ran into this issue today. [This](https://azuremachinelearningnotebooks-anandramanathan.notebooks.azure.com/j/notebooks/how-to-use-azureml/automated-machine-learning/configuration.ipynb) notebook was open/had been run couple days ago. Then today, I was not able to run it due to kernel error: Kernel error: XSRF cookie does not match POST argument. I tried to select it from the notebook root page and click Shutdown, and it does not shutdown. When I click on the notebook to launch it, it gives me the same error.

**Comment by smortaz** [comment]
@rcanand - log out, clear cookies, go incognito, try again & LMK!  thx

**Comment by rcanand** [comment]
@smortaz it does clear up by restarting all the way back (relaunching the notebook from within Azure notebooks. But I had to rerun from the beginning.

**Comment by smortaz** [comment]
@rcanand - rerunning from the beginning is generally the norm when you start a notebook instance.  in some cases, especially if you've saved intermediate files, etc., you can go to a particular cell in a notebook and select "Run cells below" from the menu to pick up where you left off...
