### ISSUE TITLE
Cannot start notebook server

### ISSUE THREAD

**Issue by Kusina** [Microsoft/AzureNotebooks#372]
Please describe your issue as completely as possible.
![image](https://user-images.githubusercontent.com/6701523/40176866-cffdd3a2-59aa-11e8-9b4f-1d2d7a5c8b86.png)

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Which language/kernel were you using when you experienced this issue?

    [] Python 3.6 

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by Kusina** [comment]
thanks for your quick response!
Just more details:
I run a machine learning algorithm yesterday and left it running to get the
results and when I can back today. It says I was forced to log out and then
I cannot restart my notebook again. 

Now I restarted my pc and it works. thanks

**Comment by smortaz** [comment]
Ah, ok.  If you look at the docs it states that after 1 hr of inactivity you are logged off...  You don't need to restart your PC.  Just log back in.   AZNB isn't meant for long running batch processes.

**Comment by DinoV** [comment]
Unfortunately I think this is a known issue with login.microsoft.com: https://stackoverflow.com/questions/46100272/azure-portal-bad-request-request-too-long

Usually you can clear your cookies to fix it, if your browser supports it I think you can clear them specifically for login.microsoft.com rather than clearing them all.
