### ISSUE TITLE
Jupyter Notebooks

### ISSUE THREAD

**Issue by AlmaAnvar** [microsoft/AzureNotebooks#380]
Please describe your issue as completely as possible.

#### Github
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Not able to open Mypython Notebook
https://notebooks.azure.com/anon-ak9sdq/libraries/samples

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by AlmaAnvar** [comment]
I am able to login in & can see my sample notes and libraries, just that
the notebooks open to a blank screen.
Ill try what you had suggested.
Thanks much!

**Comment by AlmaAnvar** [comment]
Hey, it opened when in incognito.
That was a lot of help :)

**Comment by durussel** [comment]
Hello,
Typing the "jupiter notebook" command on a terminal window when connected to my virtual machine returns a URL (http://localhost:8888/?token=...), which I am to copy/paste into a web browser in order to access my notebook according to the instructions I have. However, when doing this, I get an error message ("site can't be reached", "cannot connect to server", etc... depending on which browser I use). I tried several web browsers (Safari, Chrome, IE, Mozilla); also https, localhost:8000, without the token, Incognito on Chrome, etc... And I get the same error. I am operating under MacOS Sierra. Could someone please give me any suggestion on trying to solve this problem?
Thanks in advance for your help.
