### ISSUE TITLE
Status of AzureNotebooks

### ISSUE THREAD

**Issue by cathrynbirch** [microsoft/AzureNotebooks#381]
I am using Azure notebooks from https://notebooks.azure.com.

I get this issue when I try to open and run a Python 3.6 notebook:
Dead kernel
The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

Very simply example that won't run:
https://dataanalysisweek03-earceb.notebooks.azure.com/nb/notebooks/test_3pt6.ipynb

Time 11:25-11:50am (London, BST). I get the same issue in Firefox and Chrome. I have tried in both Windows and Linux.

Python 2.7 notebooks seem to be ok though.

I don't see an entry here for today:
https://notebooks.azure.com/status

I was wondering what the issue is. It's just an inconvenience today, which is ok but I will be teaching Python programming to undergraduates using Azure notebooks in September and I need to understand what the issue is and how likely the server is to be downtime during the class times.

Thanks.

**Comment by smortaz** [comment]
Hi @cathrynbirch  -  I just created a new 3.6 notebook and ran it and it worked fine.

![image](https://user-images.githubusercontent.com/742484/40656530-8bfad332-62f9-11e8-8cb8-84afe5eebea1.png)

Also cloned your notebook, it ran fine too:

![image](https://user-images.githubusercontent.com/742484/40656481-5ddefe56-62f9-11e8-8c29-dd286a62ea18.png)

So the problem is something else - it could be that due to some other previous operation, the kernel is in a bad state... 

* have you tried Kernel/Shutdown ?  
* go incognito and start a new session & see if it repros?

Thanks.
