### ISSUE TITLE
Installing Custom Packages 

### ISSUE THREAD

**Issue by monkeydust** [microsoft/AzureNotebooks#444]
Hi - is it possible with this service to install packages like facebook prophet one-off to my account (so I dont have to re-install each time I use the service). If not is there an azure service I could use?

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Which Web Browser(s) did you see the error in?
    [] Chrome
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by andneilmsft** [comment]
Thanks for reaching out. The Requirements feature should be able to take care of this for you: https://notebooks.azure.com/help/libraries/library-settings/environment.

If the package is not publically available then you can use the custom script feature: 
https://notebooks.azure.com/help/jupyter-notebooks/server-initialization

**Comment by ggorman** [comment]
This solution works fine for relatively small packages that are quick to install so the user does not notice the notebook startup time. However, it doesn't cut it when the packages and their dependencies take a long time to install.

We have been spitballing different potential solutions here but it's not clear what's the right way forward:
1. Just raise an issue to have whatever very important package included by default. This breaks down because sometimes specific version of a package are required and then we are back to square one.
2. Conda install everything into a virtual env and then add/commit this to the library git repo ready for cloning. The problem with this approach is that the repo could get large.
3. Another option would be to have some persistent storage containing all the dependencies that could be mounted - but I don't think this is possible with notebooks.azure currently.

Suggestions?

**Comment by smortaz** [comment]
This issue has been raised before and there are other threads on it. The
general approach proposed is to allow users to specify their own docker on
top of our base image.   That way you can put whatever packages you desire
in there and manage them with more control.

**Comment by ggorman** [comment]
Is there an open issue on the docker based solution (sounds ideal)? ETA?

While we are waiting for that support, does option (2) sound viable? We need something working for teaching in October...

**Comment by smortaz** [comment]
Yes, there's an internal issue on it that's being tracked.  No ETA yet, but it along w other related things are being worked on actively. 

There other solutions possible, but anything else takes cycles from the ideal solution which is the docker / repo2docker one.
