### ISSUE TITLE
HTML rendering of IPython.display.Audio is broken

### ISSUE THREAD

**Issue by garth-wells** [Microsoft/AzureNotebooks#47]
The HTML rendering of `IPython.display.Audio` is broken. See example at https://notebooks.azure.com/garth-wells/libraries/LSm1m3rAkXg/html/Audio.ipynb.

Running `jupyter nbconvert --to html foo.ipynb` locally produces HTML which is fine and includes an audio play button. Local Jupyter version is 4.2.1.

**Comment by DinoV** [comment]
The audio tags are disallowed because they’re unfortunately not safe for cross site scripting.  We’re using a library called bleach_whitelist which has a list of tags which are known to be safe for cross site scripting.  The underlying issue here seems to be that the tags allow JavaScript execution when they’re in the form:

<audio><source onerror="alert(1)">
	Or
<audio onerror="alert(1)"><source></source></audio>

We can presumably add audio, source, and video tags.  For audio/video we shouldn’t add any extra supported attributes.  For source we should only allow the “src” and “type” attributes.

**Comment by garth-wells** [comment]
@DinoV Would be great if you could allow the audio and video tags, Here are notebook that is affected by the video tag sanitising: <https://notebooks.azure.com/library/CUED-3D7/html/03-TimeDependentProblems.ipynb>.

**Comment by DinoV** [comment]
This is now fixed - we allow bot the audio and video tags as long as they don't attempt to do anything with JavaScript

**Comment by garth-wells** [comment]
Thanks @DinoV. Do I need to do something to refresh exiting notebooks, e.g. <https://notebooks.azure.com/library/CUED-IA-Computing-Examples-Papers/html/Examples%20Paper%202%20Guidance.ipynb>?

**Comment by DinoV** [comment]
Yes, I should have mentioned that...  You'll just need to open the notebook and save it again.  Then we'll throw away the cached version of the HTML and regenerate it on the next load.

**Comment by garth-wells** [comment]
Thanks - can confirm that it works as expected.

**Comment by garth-wells** [comment]
There appears to be a regression - this is broken again.

**Comment by DinoV** [comment]
Thanks for letting us know, I'm guessing it could have regressed with the preview support for Plotly being added, we'll take a look.

**Comment by garth-wells** [comment]
Could this issue be looked into? I've updated the URL at the top that illustrates the problem.

**Comment by DinoV** [comment]
I think the fix for this should get rolled out tomorrow.  I'll confirm after we deploy and follow up then.

**Comment by garth-wells** [comment]
Working again now.
