### ISSUE TITLE
Notebook page not responding while trying to open it

### ISSUE THREAD

**Issue by AniSin2613** [Microsoft/AzureNotebooks#475]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
While opening the notebook (for R), the web page that open is not responding and my saved code is not getting loaded.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/anisin2613/libraries/Rlib/html/CRM_RandomForest.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] R 
  

#### What time (please include time zone) did this occur?
Since 13-Sept-2018

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Internet Explorer / Edge (Please note this is not supported)    

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue?
https://notebooks.azure.com/anisin2613/libraries/Rlib/html/CRM_RandomForest.ipynb

**Comment by rachelgshaffer** [comment]
I am fairly confident this is due to the large size of the file (over 100MB), which seems to be coming from very long output of repeated string "Fully paid". Hopefully you are able to reduce the size of the output and your notebook should not have any issues. You can always the download the library and open the .ipynb file in a text editor to grab the contents you need (this is how I was able to peek into the contents). 

On our side, I am opening a bug to track this issue and see what we can do.

**Comment by andneilmsft** [comment]
Closing issue now we have an internal item to track the feature work.
