### ISSUE TITLE
SIGN IN issue on Azure Notebook

### ISSUE THREAD

**Issue by Gulrez** [Microsoft/AzureNotebooks#507]
Please describe your issue as completely as possible.
I am unable to sign in to Azure notebooks since this mornign. Tried multiple machines - same result
#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    []  Edge 

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by KieranBrantnerMagee** [comment]
Hey Gulrez; Sorry you're having this issue.  Are you able to give any detail on what happens when you fail to sign in? (Is there any error, what is the flow of pages, etc)

Would you also be able to share details regarding the account you're trying to log in from?  (If you'd preferr to share this via email, don't hesitate to ping us at nbhelp@microsoft.com)

Thanks for your patience.

**Comment by andneilmsft** [comment]
The azure issue is now mitigated. Please reactive if you are still having problems.
