### ISSUE TITLE
Notebook Kernel is Busy always

### ISSUE THREAD

**Issue by fayzaan11** [Microsoft/AzureNotebooks#541]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
This can happen for many reasons.  Can you fill out the form completely (eg link to notebook, etc.) so we can take a look?  Thx!

**Comment by fayzaan11** [comment]
[x] https://notebooks.azure.com
[] https://studio.azureml.net

[] Python 2.7 
[x] Python 3
[] Python 3.6 
[] R 
[] F#
[] Terminal

Browser
[x] Chrome
[] Firefox
[x] Internet Explorer / Edge (Please note this is not supported)
[] Other (Please Specify)

[x] Windows
[] MacOS
[] Ubuntu
[] Other (Please Specify)

Below is the screen shot and as you can see the kernel busy icon is always black. I tried to interrup the kernel and also to shutdown the kernel but it did not work. I started having this issue today i.e. 15 Nov 2018. The notebook was working fine before.
![image](https://user-images.githubusercontent.com/45058880/48533024-3e35a980-e8bc-11e8-95af-9b02882e64bf.png)

**Comment by fayzaan11** [comment]
Below is the link to the notebook
https://mtaintropythona-fayzaan.notebooks.azure.com/j/notebooks/40460_Mod02_Project2.ipynb

**Comment by smortaz** [comment]
So the problem here is the input function.  Basically input() as implemented in Jupyter (nothing to do with Azure Notebooks Service) can lock up the kernel waiting for use input.  Sometimes it works, sometimes it doesnt.  I cloned your notebook and ran a few times and each time it worked.  But i've seen input() lock up as well.  There's a long thread on it on the Jupyter team's github repo...   I'd say restart your Library and try it again.  Click in the top MD cell, then shift-enter, then enter the inputs one by one (dont skip), and it /should/ work... eg:

![image](https://user-images.githubusercontent.com/742484/48533480-8374bf80-e859-11e8-838b-e664065ed2ea.png)

**Comment by smortaz** [comment]
Hmmm... maybe I misunderstood.  You're saying /any/ notebook in that library starts as Kernel Busy?  or just the one notebook you listed which has the input() calls in it?

**Comment by fayzaan11** [comment]
It was all the notebooks in this particular library. I tried some of the first notebooks in section 1.x, the ones in 2.x and 3a. All of them had their kernel busy. 

Fun fact, i re read your comment and the lock on thing about input() hit me so i tried spamming the stop button in the notebook like so many times (after trying what you said) and the kernel is now okay.
I'm not saying its a fix, i think they should look into it so that other people don't go crazy over this simple issue.

**Comment by smortaz** [comment]
Interesting.  I'd say shutdown the kernel (using shutdown at the Library list level).  Then log out, clear cookies and retry & see if that clears the state sufficiently.

Regarding the fix for input() - that has to come from the Jupyter team... We've also told instructors not to use input() but they keep doing it... it's broken.

**Comment by fayzaan11** [comment]
Okay. If I encounter this issue again I shall try this to see if it helps.

Oh okay. I shall pass on the message to anyone else I know using the input() command in Jupyter Notebooks.

P.S: Leaving this Thread open in case I or someone else encounters same issue.

**Comment by smortaz** [comment]
Sounds good.  Thx & sorry for the troubles...

**Comment by afelthe** [comment]
I am experiencing the same issue.  Cannot resolve it. Kernel always busy with Chrome and Python 3.6.
