### ISSUE TITLE
opening a blank new notebook issue - the add button only lets you close, not create

### ISSUE THREAD

**Issue by calcqu** [Microsoft/AzureNotebooks#61]
Please consider the template below to file your issue. 

### Description
First, when clicking get started you get sent to a page not found - smh.

Then when clicking libraries in the bar above, I want to add a library, that works, then I want to add a notebook but the pop up only lets me type a name, and a language but then does nothing more than close, via the close button without creating a new notebook for use!   

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
apologies - we are aware & will be fixed soon.

when adding a notebook name, you need to supply the ".ipynb" part.
 elsewhere it's added, here it's not.  fix coming.

**Comment by crwilcox** [comment]
@calcqu , there was a 'submit' button but it was disabled/greyed out unless your input is valid. The input needed to have an ipynb extension. The bug was we weren't providing appropriate feedback to let you know that. I apologize for that.

It is fixed in production and should work well now.

Thanks for helping to improve our product!
Chris
