### ISSUE TITLE
Unable to re-start existing project

### ISSUE THREAD

**Issue by am4096** [Microsoft/AzureNotebooks#631]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I am not able to change the status of my projects - they currently show "Stopped"

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/am4096/projects

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [x] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Still happening now

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/am4096/projects

**Comment by andneilmsft** [comment]
Could you include a screenshot of what you see?

**Comment by am4096** [comment]
Please see the screen shot below. This is what I get in Chrome, even after
clicking the blue tab / button many times. Looking forward to hearing from
you,
A.

[image: image.png]

**Comment by andneilmsft** [comment]
thanks for sharing the screenshot, however i am not able to see it. Can you try again? if you are replying via email, it might work better to upload the screenshot via the github webpage.

**Comment by andneilmsft** [comment]
please reactivate when you are able to provide more information. 

thank you!

**Comment by am4096** [comment]
Hi Andrew,

thanks for persisting with this case. There is a lecture-cum-demonstration
event here on the 13th (next Wednesday). Would it be possible to bring it
up then?

Warm regards,

Abhijit

**Comment by andneilmsft** [comment]
Please restate your question.  We were not able to investigate your problem because the screenshot did not appear in the ticket. Please restate the steps needed to reproduce the problem and ensure the include screenshot is visible. I recommend using the GitHub site to share this info rather than replying to this email directly.

**Comment by am4096** [comment]
It seems you did not read my previous email. Would you please do so and
advise.

Warm regards,

Abhijit

**Comment by andneilmsft** [comment]
Previous reply has been read. The screenshot did not appear. Please use github to attach the screenshot. Please restate the steps you take, what you expect to happen and what actually happened. This will enable us to help you.

**Comment by am4096** [comment]
Hi Andrew,

The e-mail that I am referring to is about the prospect of meeting you in
London, nothing to do with screenshots. I am surprised that you did not
react to the proposal that I made. This is why I got the impression of you
not reading the e-mail. However, if you did read it, then you should react
to the proposal, either way. Regarding the screenshot problem, it seems
that there is a work-around the problem that was bothering me. What I am
interested in is how I can I upload medium size data files (< 10 GB) to
Azure to work with.

I look forward to hearing from you,

Warm regards,

Abhijit Mandal

**Comment by andneilmsft** [comment]
The Azure notebooks team does not have a presence in London. 

10GB files are best stored externally to azure notebooks. We only support 100mb files in the project. This is by design, because the project system is not a big data system.  We recommend you pull the data from that external store into notebook in chunks and consume it that way. Alternatively, you might have more success keeping the data in a big data system such as HD Insights, Azure Machine learning or Azure Data lake and making Azure SDK calls from the notebook to do heavy lifting within those system and only pull the results back into the notebook. 


https://notebooks.azure.com/azureml/projects/azureml-getting-started

https://notebooks.azure.com/Microsoft/projects/2018-data-access/html/Access%20your%20data%20in%20Azure%20Notebooks.ipynb
