### ISSUE TITLE
%%script false at top of cell doesn't work

### ISSUE THREAD

**Issue by davidefiocco** [microsoft/AzureNotebooks#637]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

`%%script false` in Jupyter should avoid the content of a cell to be executed (see e.g. https://forums.fast.ai/t/jupyter-notebook-enhancements-tips-and-tricks/17064/4).
When running a cell containing it, I get a `CalledProcessError` instead.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Type in a Azure notebook using Direct compute a cell containing

    %%script false 
    1+1

That yields me

> Command 'b'1+1\n'' returned non-zero exit status 1.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

Sat Feb 16 20:19:39 CEST 2019

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by stas00** [comment]
I'm not sure where I originally found the `%%script false` trick, but indeed it no longer works.
Since that behavior was never documented (or was intended) they must have dropped it in the recent versions of ipython.

Here are some other tricks, based on programs ignoring their arguments when you tell them not to expect any. 

Perl:

    %%perl -e0
    ​
    for i in range(10): print(i)

Here you're running: `perl -e '0' cellcontents`

A more memorable version:

    %%perl -eignorethis
    ​
    for i in range(10): print(i)

Here you're running: `perl -e 'ignorethis' cellcontents`

Bash (':' is a noop in bash)

    %%bash -c ':'
    
    for i in range(10): print(i)
    
':' is a noop in bash, so you're running: `bash -c ':' cellcontents`

I'm sure you can come up with other creative solutions, by looking at the supported programs here: https://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics

**Comment by davidefiocco** [comment]
`%%script false --no-raise-error`

Works fine also on Azure Notebooks, so the issue can be closed.
