### ISSUE TITLE
My project cannot run

### ISSUE THREAD

**Issue by johnsonjmaliakal** [microsoft/AzureNotebooks#715]
#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
I am unable to run my project. Every time I run a notebook within my project, it responds with an error message that says:

Your notebook server is automatically shutdown after a 1 hour period of inactivity. Any files in your 'project' folder will be persisted after the lifetime of the notebook. All other files and state will be discarded.

You can restart your notebook server by clicking on the button below.

(Button says 'Restart notebook server')

When I click the button, it says:
 Your notebook server appears to be unresponsive.
This could be an intermittent connectivity issue so you can try connecting to it again . If your notebook doesn't respond or returns you back here then click the button to restart the notebook server.
(Button says 'Restart notebook server')

Later, just to see what works, I converted the project from private to public. Now, whenever I open notebook in the project, it just redirects to another tab with the project open. 

I then tried to create a new project so that I could at least save my files, but that project appears to have the same issue.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/ScalyV/projects/lalu
https://notebooks.azure.com/ScalyV/projects/i-m-confused
#### Which language/kernel were you using when you experienced this issue?

    [x] Python 3.6 

BUT, the notebook hadn't run yet, so technically none of them.

#### What time (please include time zone) did this occur?
11:15 (UTC +4:00)

#### Which Web Browser(s) did you see the error in?
    [x] Other (Please Specify)
    Safari

#### Which Operating System are you using? Please specify version as well if possible:
   [x] MacOS
macOS Mojave 10.14.5

#### What is the path to the notebook file (if relevant) that reproduces the issue? 
Uhh, to be honest, it doesn't seem to make any difference. So, irrelevant.

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

It asks me to input this into a cell in a notebook, but I CAN'T open a notebook.

**Comment by johnsonjmaliakal** [comment]
I had tried later in around three days, and it worked perfectly, so I was considering closing this issue, but it started acting up again today with another project that I had opened up.
https://notebooks.azure.com/ScalyV/projects/holiday-assignment
This is the link for the same.

**Comment by KieranBrantnerMagee** [comment]
Hey Johnson,
apologies for taking so long to follow up, thanks for pinging again.

We've seen similar symptoms recently reported by other users, wherein you are signed out behind the scenes, and because the project in question is private, you'll see errors when trying to run it; this has largely started occuring since we defaulted to private-projects-on-creation for security reasons.

In the interim a workaround would likely be hitting sign out -> re-signing in. (If a bigger hammer is needed, a new browser session/incognito session would certainly do the trick)  Feel free to reopen if this recurs and the workaround is not helpful.

We've taken the feedback to try and improve the UX presented to avoid future confusion.

Thanks so much for your patience and for using Notebooks.
Best,
-Kieran

**Comment by johnsonjmaliakal** [comment]
Hey man, thanks for the fix!
Just wanted to say that, yes, indeed, it does seem to be fine, but occasionally, it does have the same issue again. When I return to it a couple of hours later, it disappears. I tried this a couple of times, and it keeps recurring.

**Comment by johnsonjmaliakal** [comment]
I tried using multiple computers, browsers, browser windows, and even multiple operating systems! It still sorta kinda persists. I do still love this product though and can't imagine what I would do without it.

**Comment by johnsonjmaliakal** [comment]
Additionally, I didn't come across this issue when the security default was introduced.

**Comment by johnsonjmaliakal** [comment]
And no, the project that I had linked was not private, it was initially private, and even when I had the project settings changed to Public, the issue persisted, albeit in a different way, which I will open in another issue.

**Comment by KieranBrantnerMagee** [comment]
You'll have to excuse my assumption, I was basing it off of the link to "https://notebooks.azure.com/ScalyV/projects/i-m-confused"

For the purposes of posterity going to use this thread and reopening this, since it has more context related to your issue, and the history of the conversation.

Re: security default, the issue would have existed prior, that change just surfaced it more visibly, so your statement doesn't entirely contradict that.  The detail is appreciated, however.

Digging deeper into our logs for the "https://notebooks.azure.com/ScalyV/projects/holiday-assignment" project, did you see the occurrences of this failure once on the 15th, and once on the 16th?

If that's the case, I saw a similar occurence for your "i-m-confused" project, which is the same symptom as I've come to expect from the permission expiry issue I mentioned above.  It would occur (hopefully only sporadically) across browsers/computers/etc if you used each enough, my suggestion was only to essentially refresh your session when the bug occurs to work around the issue and immediately give you access again.  If I've misunderstood, don't hesitate to let me know.

Feel free to chime in here if it recurs again and I'll sanity check that it is in fact the same pattern we're seeing on the backend.

**Comment by johnsonjmaliakal** [comment]
Yes, I did indeed see the error message popup on the mentioned dates, and I simply close the tabs, waited a couple of hours, and it worked.

**Comment by johnsonjmaliakal** [comment]
I also did what you had recommended a couple of comments ago (signing out -> signing back in), and it worked like a charm.

**Comment by johnsonjmaliakal** [comment]
All the same, I do think that you shouldn't simply ask others (me excluded, I don't care) to sign out and back, they might find it inefficient. All I'm saying is, find a fix to it all the same.
On that note, I think I'll close this issue now.
Thanks!

**Comment by KieranBrantnerMagee** [comment]
To be very clear, the sign out/in is _only_ a workaround as we try to come up with a better experience; this is not a scenario we are happy with (clearly as it causes confusion) and your help in diagnosing this has been very appreciated.

Thanks again for your time, always feel free to ping us if any issues!
