### ISSUE TITLE
upload notebook to existing library

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/AzureNotebooks#96]
### Description
Cannot upload notebook to existing library

### Repro Steps
no upload button or path to view library in jupyter to use upload after library is created

### Usage Scenario 
Teacher adding files at a specific point in class
Adding additional notebooks to a project that were developed elsewhere

### Recommended Metadata
Python 3, general library interface
Occurrence Time: 4:30 5/15/17
Web Browser: edge
LibraryID and Notebook Name (if applicable): any

**Comment by smortaz** [comment]
when in the library, click on +New.  that'll give you 3 ways to upload a notebook:

![image](https://cloud.githubusercontent.com/assets/742484/26084229/870421b0-398f-11e7-90bf-f44fd77842b9.png)

**Comment by smortaz** [comment]
also, when in Jupyter, click the Jupyter icon on top left and then in the tree view, click "New" (top right) to upload a notebook.

**Comment by bospoort** [comment]
When I try to add a notebook from a github url, I have to go to 'raw' first. It took me moment and the import error one gets is not super informative. It would be great if you could just import from the md url. E.g. https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_101_LogisticRegression.ipynb

Copying over a full directory of notebooks would be great too (instead of just individual docs)

**Comment by smortaz** [comment]
thanks bospoort - full github load, including /data/ is coming soon.  we'll
improve the msg about raw too.  thanks!

**Comment by eric-camplin** [comment]
definitely workarounds - if in library can only upload from github.  
do see that can create a new library (empty) and then add files
